---
title: "Bayes_modeling"
author: "Cheyenne Erickson, Yumna Rizvi, Bo Zhou, Ben Davidson"
date: "2026-05-04"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Bayesian Model - regression with GDP, social support, freedom, and corruption, life expectancy

```{r}
#data <- read.csv("C://Users/yumna/Downloads/2019.csv")
data <- X2019

```

```{r}
X_raw <- model.matrix(~ `GDP per capita` + `Social support` + 
                  `Freedom to make life choices` + 
                  `Healthy life expectancy` + 
                  `Perceptions of corruption`, data = data)

# scale/normalize except intercept
X <- X_raw
X[, -1] <- scale(X[, -1], center = TRUE, scale = FALSE)

```


```{r}
Y <- data$Score
```

Prior Specifications:

```{r}
Mu <- c(0, 0, 0, 0)
# explain why we chose the g, a, and b
g <- 5 # our dimension p in n vs p (n = 157, p = 5)
a <-.001
b <-.001 # weak informative
```

```{r}
gibbs_sampler <- function(Y, X, n_iter = 5000, burn = 1000,
                          g = 5, a = 0.001, b = 0.001) {

  n <- length(Y)
  p <- ncol(X)

  # storage
  beta_samples <- matrix(0, n_iter, p)
  phi_samples  <- numeric(n_iter)

  # initial values
  beta <- rep(0, p)
  phi  <- 1

  # precompute
  XtX <- t(X) %*% X
  XtY <- t(X) %*% Y
  I_p <- diag(p)

  V_beta_base <- solve(XtX + (1/g) * I_p)   # no phi here

  for (t in 1:n_iter) {

    # sample beta | phi, y conditional for gibbs
    V_beta <- (1/phi) * V_beta_base
    m_beta <- V_beta_base %*% XtY

    beta <- MASS::mvrnorm(1, mu = m_beta, Sigma = V_beta)

    # sample phi | beta, y conditional for gibbs
    residual <- Y - X %*% beta

    a_star <- a + (n + p)/2
    b_star <- b + 0.5 * (t(residual) %*% residual +
                         (1/g) * t(beta) %*% beta)

    phi <- rgamma(1, shape = a_star, rate = b_star)

    # store
    beta_samples[t, ] <- beta
    phi_samples[t] <- phi
  }

  # remove burn-in
  list(
    beta = beta_samples[(burn+1):n_iter, ],
    phi  = phi_samples[(burn+1):n_iter]
  )
}


library(MASS)

result <- gibbs_sampler(Y, X)
```


```{r}
# posterior means summary
colMeans(result$beta)
mean(result$phi)

coef_labels <- c(
  "Beta_0: Intercept",
  "Beta_1: GDP per capita",
  "Beta_2: Social support",
  "Beta_3: Freedom",
  "Beta_4: Life expectancy",
  "Beta_5: Corruption"
)


# Give beta columns meaningful names
beta_names <- coef_labels

# Set plotting layout: 3 rows x 2 columns for 6 betas
par(mfrow = c(3, 2), mar = c(4, 4, 3, 1))

# Trace plot for each beta
for (j in 1:ncol(result$beta)) {
  plot(
    result$beta[, j],
    type = "l",
    main = paste("Trace Plot for", beta_names[j]),
    xlab = "Iteration",
    ylab = expression(beta),
    col = "black"
  )
}

plot(result$phi, type = "l")

# histograms
hist(result$phi)


# CI
apply(result$beta, 2, quantile, c(0.025, 0.975))
# compare with regular OLS (we will see how much the prior changed our data when we compare bayesian results to OLS)
lm(Y ~ X[, -1])
# posterior predictive (we'll choose if we want to continue this)
y_hat <- X %*% t(result$beta)
y_hat
```
convergence test for betas:
```{r}
library(coda)
# Geweke z-scores for each beta
geweke_beta_z <- apply(result$beta, 2, function(chain) {
  geweke.diag(as.mcmc(chain), frac1 = 0.1, frac2 = 0.5)$z
})

# Convert z-scores to two-sided p-values
geweke_beta_p <- 2 * (1 - pnorm(abs(geweke_beta_z)))

# Put results in a table
geweke_beta_results <- data.frame(
  Parameter = colnames(X),
  Geweke_Z = geweke_beta_z,
  P_value = geweke_beta_p
)

geweke_beta_results

```
for phi:
```{r}
geweke_phi_z <- geweke.diag(as.mcmc(result$phi), frac1 = 0.1, frac2 = 0.5)$z

geweke_phi_p <- 2 * (1 - pnorm(abs(geweke_phi_z)))

geweke_phi_results <- data.frame(
  Parameter = "phi",
  Geweke_Z = geweke_phi_z,
  P_value = geweke_phi_p
)

geweke_phi_results

```

histograms for betas and phi:
```{r}
# Histograms for each beta
par(mfrow = c(3, 2), mar = c(4, 4, 3, 1))

for (j in 1:ncol(result$beta)) {
  hist(
    result$beta[, j],
    breaks = 30,
    main = paste("Posterior Histogram for", beta_names[j]),
    xlab = beta_names[j],
    col = "gray",
    border = "white"
  )
}

```

for phi:
```{r}
# Reset plotting layout
par(mfrow = c(1, 1))

hist(
  result$phi,
  breaks = 30,
  main = expression("Posterior Histogram for " * phi),
  xlab = expression(phi),
  col = "gray",
  border = "white"
)

```

```{r}
result
```

